name: ci pipeline
on:
    workflow_dispatch:
      inputs: 
        version:
          description: 'Version of the package'
          required: true
          default: 'latest'

jobs:
    ci:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
        - uses: actions/checkout@v4
        - name: Build image
          run: docker build . --file Dockerfile --tag ghcr.io/nimeshadil/web:${{ github.event.inputs.version }}
        - name: Log in to registry
          run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ secrets.USER }} --password-stdin
        - name: Push image
          run: docker push ghcr.io/nimeshadil/web:${{ github.event.inputs.version }}